services:
  # ------ MongoDB ------
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  db-data:
